// Auto-generated by NexusV VerilogEmitter
// Graph: crc_step  |  Latency: 4 cycle(s)

module crc_step (
    input  logic        clk_i,
    input  logic        rst_ni,
    input  logic        start_i,
    input  logic [31:0] rs1_i,
    input  logic [31:0] rs2_i,
    output logic [31:0] rd_o,
    output logic        done_o
);

    // Combinational result wires
    logic [31:0] n5_comb;
    logic [31:0] n4_comb;
    logic [31:0] n6_comb;
    logic [31:0] n8_comb;

    // Pipeline stage registers
    logic [31:0] n5_r2;
    logic [31:0] n4_r2;
    logic [31:0] n6_r3;
    logic [31:0] n8_r4;

    logic [3:0] done_shift;

    // Combinational logic
    assign n5_comb = rs1_i & 32'd1;
    assign n4_comb = rs1_i >> 32'd1;
    assign n6_comb = |n5_r2 ? 32'd79764919 : 32'd0;
    assign n8_comb = n4_r2 ^ n6_r3;

    always_ff @(posedge clk_i or negedge rst_ni) begin
        if (!rst_ni) begin
            n5_r2 <= '0;
            n4_r2 <= '0;
            n6_r3 <= '0;
            n8_r4 <= '0;
        end else begin
            n5_r2 <= n5_comb;
            n4_r2 <= n4_comb;
            n6_r3 <= n6_comb;
            n8_r4 <= n8_comb;
        end
    end

    assign rd_o = n8_r4;

    always_ff @(posedge clk_i or negedge rst_ni) begin
        if (!rst_ni) begin
            done_shift <= '0;
        end else begin
            done_shift <= {done_shift[2:0], start_i};
        end
    end

    assign done_o = done_shift[3];

endmodule
