// Auto-generated by NexusV VerilogEmitter
// Graph: horner_poly  |  Latency: 10 cycle(s)

module horner_poly (
    input  logic        clk_i,
    input  logic        rst_ni,
    input  logic        start_i,
    input  logic        stall_i,
    input  logic [31:0] rs1_i,
    input  logic [31:0] rs2_i,
    input  logic [31:0] rs3_i,
    input  logic [31:0] rs4_i,
    input  logic [31:0] rs5_i,
    output logic [31:0] rd_o,
    output logic        done_o
);

    // Combinational result wires
    logic [31:0] n7_comb;
    logic [31:0] n8_comb;
    logic [31:0] n6_comb;
    logic [31:0] n10_comb;
    logic [31:0] n11_comb;
    logic [31:0] n9_comb;

    // Pipeline stage registers
    logic [31:0] n7_r4;
    logic [31:0] n8_r5;
    logic [31:0] n8_r6;
    logic [31:0] n6_r2;
    logic [31:0] n6_r3;
    logic [31:0] n10_r8;
    logic [31:0] n10_r9;
    logic [31:0] n11_r10;
    logic [31:0] n9_r7;

    logic [9:0] done_shift;

    // Combinational logic
    assign n6_comb = rs1_i * rs2_i;
    assign n7_comb = n6_r3 + rs3_i;
    assign n8_comb = n7_r4 * rs2_i;
    assign n9_comb = n8_r6 + rs4_i;
    assign n10_comb = n9_r7 * rs2_i;
    assign n11_comb = n10_r9 + rs5_i;

    always_ff @(posedge clk_i or negedge rst_ni) begin
        if (!rst_ni) begin
            n7_r4 <= '0;
            n8_r5 <= '0;
            n8_r6 <= '0;
            n6_r2 <= '0;
            n6_r3 <= '0;
            n10_r8 <= '0;
            n10_r9 <= '0;
            n11_r10 <= '0;
            n9_r7 <= '0;
        end else if (!stall_i) begin
            n7_r4 <= n7_comb;
            n8_r5 <= n8_comb;
            n8_r6 <= n8_r5;
            n6_r2 <= n6_comb;
            n6_r3 <= n6_r2;
            n10_r8 <= n10_comb;
            n10_r9 <= n10_r8;
            n11_r10 <= n11_comb;
            n9_r7 <= n9_comb;
        end
    end

    assign rd_o = n11_r10;

    always_ff @(posedge clk_i or negedge rst_ni) begin
        if (!rst_ni) begin
            done_shift <= '0;
        end else if (!stall_i) begin
            done_shift <= {done_shift[8:0], start_i};
        end
    end

    assign done_o = done_shift[9];

endmodule
