// Auto-generated by NexusV VerilogEmitter
// Graph: mac_plus_5  |  Latency: 4 cycle(s)

module mac_plus_5 (
    input  logic        clk_i,
    input  logic        rst_ni,
    input  logic        start_i,
    input  logic [31:0] rs1_i,
    input  logic [31:0] rs2_i,
    output logic [31:0] rd_o,
    output logic        done_o
);

    // Combinational result wires
    logic [31:0] n5_comb;
    logic [31:0] n4_comb;

    // Pipeline stage registers
    logic [31:0] n5_r4;
    logic [31:0] n4_r2;
    logic [31:0] n4_r3;

    logic [3:0] done_shift;

    // Combinational logic
    assign n4_comb = rs1_i * rs2_i;
    assign n5_comb = n4_r3 + 32'd5;

    always_ff @(posedge clk_i or negedge rst_ni) begin
        if (!rst_ni) begin
            n5_r4 <= '0;
            n4_r2 <= '0;
            n4_r3 <= '0;
        end else begin
            n5_r4 <= n5_comb;
            n4_r2 <= n4_comb;
            n4_r3 <= n4_r2;
        end
    end

    assign rd_o = n5_r4;

    always_ff @(posedge clk_i or negedge rst_ni) begin
        if (!rst_ni) begin
            done_shift <= '0;
        end else begin
            done_shift <= {done_shift[2:0], start_i};
        end
    end

    assign done_o = done_shift[3];

endmodule
