// Auto-generated by NexusV DispatcherEmitter
// 4 datapath(s) behind mux

module nexus_mux (
    input  logic        clk_i,
    input  logic        rst_ni,
    input  logic        start_i,
    input  logic [2:0]  funct3_i,
    input  logic [31:0] rs1_i,
    input  logic [31:0] rs2_i,
    output logic [31:0] rd_o,
    output logic        done_o
);

    // Per-datapath handshake signals
    logic        start_0;
    logic        done_0;
    logic [31:0] rd_0;
    logic        start_1;
    logic        done_1;
    logic [31:0] rd_1;
    logic        start_2;
    logic        done_2;
    logic [31:0] rd_2;
    logic        start_3;
    logic        done_3;
    logic [31:0] rd_3;

    // Dispatch selection latch
    logic [2:0] selected_q;
    logic       inflight_q;  // 1 while a datapath is computing

    always_ff @(posedge clk_i or negedge rst_ni) begin
        if (!rst_ni) begin
            selected_q <= '0;
            inflight_q <= 1'b0;
        end else begin
            if (start_i && !inflight_q) begin
                selected_q <= funct3_i;
                inflight_q <= 1'b1;
            end else if (done_o) begin
                inflight_q <= 1'b0;
            end
        end
    end

    // Start routing — one-hot to selected datapath
    assign start_0 = start_i && (funct3_i == 3'd0) && !inflight_q;
    assign start_1 = start_i && (funct3_i == 3'd1) && !inflight_q;
    assign start_2 = start_i && (funct3_i == 3'd2) && !inflight_q;
    assign start_3 = start_i && (funct3_i == 3'd3) && !inflight_q;

    // Datapath instantiations
    mac_plus_5 u_dp_0 (
        .clk_i   (clk_i),
        .rst_ni  (rst_ni),
        .start_i (start_0),
        .rs1_i   (rs1_i),
        .rs2_i   (rs2_i),
        .rd_o    (rd_0),
        .done_o  (done_0)
    );

    crc_step u_dp_1 (
        .clk_i   (clk_i),
        .rst_ni  (rst_ni),
        .start_i (start_1),
        .rs1_i   (rs1_i),
        .rs2_i   (rs2_i),
        .rd_o    (rd_1),
        .done_o  (done_1)
    );

    nexus_simd_mac u_dp_2 (
        .clk_i   (clk_i),
        .rst_ni  (rst_ni),
        .start_i (start_2),
        .rs1_i   (rs1_i),
        .rs2_i   (rs2_i),
        .rd_o    (rd_2),
        .done_o  (done_2)
    );

    nexus_saturating_add u_dp_3 (
        .clk_i   (clk_i),
        .rst_ni  (rst_ni),
        .start_i (start_3),
        .rs1_i   (rs1_i),
        .rs2_i   (rs2_i),
        .rd_o    (rd_3),
        .done_o  (done_3)
    );

    // Return mux — route selected datapath's result back
    always_comb begin
        rd_o   = '0;
        done_o = 1'b0;
        case (selected_q)
            3'd0: begin
                rd_o   = rd_0;
                done_o = done_0;
            end
            3'd1: begin
                rd_o   = rd_1;
                done_o = done_1;
            end
            3'd2: begin
                rd_o   = rd_2;
                done_o = done_2;
            end
            3'd3: begin
                rd_o   = rd_3;
                done_o = done_3;
            end
            default: ;
        endcase
    end

endmodule
