// Auto-generated by NexusV DispatcherEmitter
// 1 stateful + 5 stateless datapath(s) behind mux

// Stateful command encoding (funct3 0–2)
localparam logic [2:0] CMD_WRITE_ADDR = 3'd0;
localparam logic [2:0] CMD_WRITE_DATA = 3'd1;
localparam logic [2:0] CMD_START = 3'd2;

module nexus_mux (
    input  logic        clk_i,
    input  logic        rst_ni,
    input  logic        start_i,
    input  logic        stall_i,
    input  logic [ 2:0] funct3_i,
    input  logic [31:0] rs1_i,
    input  logic [31:0] rs2_i,
    output logic [31:0] rd_o,
    output logic        done_o,
    output logic [31:0] sp_addr_o,
    output logic [31:0] sp_wdata_o,
    output logic        sp_we_o,
    input  logic [31:0] sp_rdata_i
);

  // Stateful configuration registers (latched via commands)
  logic [31:0] stateful_addr_q;
  logic [31:0] stateful_wdata_q;
  logic        stateful_we;  // pulsed on CMD_WRITE_DATA
  logic        stateful_start;  // pulsed on CMD_START
  logic        stateful_done;
  logic [31:0] stateful_rd;

  always_ff @(posedge clk_i or negedge rst_ni) begin
    if (!rst_ni) begin
      stateful_addr_q  <= '0;
      stateful_wdata_q <= '0;
    end else if (start_i && !done_o) begin
      unique case (funct3_i)
        CMD_WRITE_ADDR: stateful_addr_q <= rs1_i;
        CMD_WRITE_DATA: stateful_wdata_q <= rs1_i;
        default: ;
      endcase
    end
  end

  // Command pulse generators (1 cycle, qualified by start_i)
  assign stateful_we    = start_i && !done_o && (funct3_i == CMD_WRITE_DATA);
  assign stateful_start = start_i && !done_o && (funct3_i == CMD_START);

  // Per-datapath handshake signals
  logic        start_3;
  logic        done_3;
  logic [31:0] rd_3;
  logic        start_4;
  logic        done_4;
  logic [31:0] rd_4;
  logic        start_5;
  logic        done_5;
  logic [31:0] rd_5;
  logic        start_6;
  logic        done_6;
  logic [31:0] rd_6;
  logic        start_7;
  logic        done_7;
  logic [31:0] rd_7;

  // Dispatch selection latch — remembers which path is busy
  logic [ 2:0] selected_q;
  logic        inflight_q;

  always_ff @(posedge clk_i or negedge rst_ni) begin
    if (!rst_ni) begin
      selected_q <= '0;
      inflight_q <= 1'b0;
    end else begin
      if (start_i && (!inflight_q || done_o)) begin
        selected_q <= funct3_i;
        inflight_q <= 1'b1;
      end else if (done_o) begin
        inflight_q <= 1'b0;
      end
    end
  end

  // Stateless start routing — one-hot based on funct3 >= 3
  assign start_3 = start_i && (funct3_i == 3'd3) && (!inflight_q || done_o);
  assign start_4 = start_i && (funct3_i == 3'd4) && (!inflight_q || done_o);
  assign start_5 = start_i && (funct3_i == 3'd5) && (!inflight_q || done_o);
  assign start_6 = start_i && (funct3_i == 3'd6) && (!inflight_q || done_o);
  assign start_7 = start_i && (funct3_i == 3'd7) && (!inflight_q || done_o);

  // Stateful datapath — commands routed via funct3 0-2
  nexus_mont_adapter u_stateful (
      .clk_i  (clk_i),
      .rst_ni (rst_ni),
      .stall_i(stall_i),
      .start_i(stateful_start),
      .rs1_i  (rs1_i),
      .rs2_i  (rs2_i),
      .addr_i (stateful_addr_q),
      .wdata_i(stateful_wdata_q),
      .we_i   (stateful_we),
      .rd_o   (stateful_rd),
      .done_o (stateful_done),
      .sp_addr_o(sp_addr_o),
      .sp_wdata_o(sp_wdata_o),
      .sp_we_o(sp_we_o),
      .sp_rdata_i(sp_rdata_i)
  );

  // Stateless datapath instantiations
  mac_plus_5 u_dp_3 (
      .clk_i  (clk_i),
      .rst_ni (rst_ni),
      .start_i(start_3),
      .stall_i(stall_i),
      .rs1_i  (rs1_i),
      .rs2_i  (rs2_i),
      .rd_o   (rd_3),
      .done_o (done_3)
  );

  crc_step u_dp_4 (
      .clk_i  (clk_i),
      .rst_ni (rst_ni),
      .start_i(start_4),
      .stall_i(stall_i),
      .rs1_i  (rs1_i),
      .rs2_i  (rs2_i),
      .rd_o   (rd_4),
      .done_o (done_4)
  );

  nexus_simd_mac u_dp_5 (
      .clk_i  (clk_i),
      .rst_ni (rst_ni),
      .start_i(start_5),
      .stall_i(stall_i),
      .rs1_i  (rs1_i),
      .rs2_i  (rs2_i),
      .rd_o   (rd_5),
      .done_o (done_5)
  );

  nexus_saturating_add u_dp_6 (
      .clk_i  (clk_i),
      .rst_ni (rst_ni),
      .start_i(start_6),
      .stall_i(stall_i),
      .rs1_i  (rs1_i),
      .rs2_i  (rs2_i),
      .rd_o   (rd_6),
      .done_o (done_6)
  );

  nexus_barrett_reduction u_dp_7 (
      .clk_i  (clk_i),
      .rst_ni (rst_ni),
      .start_i(start_7),
      .stall_i(stall_i),
      .rs1_i  (rs1_i),
      .rs2_i  (rs2_i),
      .rd_o   (rd_7),
      .done_o (done_7)
  );

  // Return mux — route back from the selected path
  always_comb begin
    rd_o   = '0;
    done_o = 1'b0;
    case (selected_q)
      CMD_WRITE_ADDR, CMD_WRITE_DATA, CMD_START: begin
        rd_o   = stateful_rd;
        done_o = stateful_done;
      end
      3'd3: begin
        rd_o   = rd_3;
        done_o = done_3;
      end
      3'd4: begin
        rd_o   = rd_4;
        done_o = done_4;
      end
      3'd5: begin
        rd_o   = rd_5;
        done_o = done_5;
      end
      3'd6: begin
        rd_o   = rd_6;
        done_o = done_6;
      end
      3'd7: begin
        rd_o   = rd_7;
        done_o = done_7;
      end
      default: ;
    endcase
  end

endmodule
