# DispatcherEmitter.jl
#
# Auto-generates nexus_mux.sv from a build manifest.
# The mux sits between cvxif_nexus_shell and N datapaths,
# decoding funct3 to route issue/result handshakes.

export DatapathEntry, emit_dispatcher

# One entry in the build manifest — metadata for a single datapath.
struct DatapathEntry
    module_name::String      # "mac_plus_5"
    funct3_id::Int           # 0–7, dispatch key from CV-X-IF instruction
    latency::Int             # pipeline depth in cycles
    is_stateful::Bool        # true if scratchpad-backed (extra ports)
    file_path::String        # relative to hw/rtl/, e.g. "mac_plus_5.sv"
end

# Generate nexus_mux.sv from a list of DatapathEntry records.
#
# The mux:
#   - Decodes funct3_i on issue, asserts start_i only to the selected datapath
#   - Latches the selection so the return path knows which datapath to listen to
#   - Muxes rd_o / done_o from the selected datapath back to the shell
#
# All datapaths share a canonical port list:
#   clk_i, rst_ni, start_i, rs1_i, rs2_i, rd_o, done_o
function emit_dispatcher(entries::Vector{DatapathEntry}, filepath::String)
    W = 32
    N = length(entries)
    N == 0 && error("Manifest must contain at least one datapath entry")

    # Validate funct3 IDs
    ids = [e.funct3_id for e in entries]
    length(unique(ids)) == N || error("Duplicate funct3_id in manifest")
    all(0 .<= ids .<= 7) || error("funct3_id must be in 0..7")

    lines = String[]

    push!(lines, "// Auto-generated by NexusV DispatcherEmitter")
    push!(lines, "// $(N) datapath(s) behind mux")
    push!(lines, "")
    push!(lines, "module nexus_mux (")
    push!(lines, "    input  logic        clk_i,")
    push!(lines, "    input  logic        rst_ni,")
    push!(lines, "    input  logic        start_i,")
    push!(lines, "    input  logic [2:0]  funct3_i,")
    push!(lines, "    input  logic [$(W-1):0] rs1_i,")
    push!(lines, "    input  logic [$(W-1):0] rs2_i,")
    push!(lines, "    output logic [$(W-1):0] rd_o,")
    push!(lines, "    output logic        done_o")
    push!(lines, ");")
    push!(lines, "")

    # Per-datapath start / done / rd wires
    push!(lines, "    // Per-datapath handshake signals")
    for e in entries
        push!(lines, "    logic        start_$(e.funct3_id);")
        push!(lines, "    logic        done_$(e.funct3_id);")
        push!(lines, "    logic [$(W-1):0] rd_$(e.funct3_id);")
    end
    push!(lines, "")

    # Selection latch — captures funct3 on issue, holds through pipeline drain
    push!(lines, "    // Dispatch selection latch")
    push!(lines, "    logic [2:0] selected_q;")
    push!(lines, "    logic       inflight_q;  // 1 while a datapath is computing")
    push!(lines, "")
    push!(lines, "    always_ff @(posedge clk_i or negedge rst_ni) begin")
    push!(lines, "        if (!rst_ni) begin")
    push!(lines, "            selected_q <= '0;")
    push!(lines, "            inflight_q <= 1'b0;")
    push!(lines, "        end else begin")
    push!(lines, "            if (start_i && !inflight_q) begin")
    push!(lines, "                selected_q <= funct3_i;")
    push!(lines, "                inflight_q <= 1'b1;")
    push!(lines, "            end else if (done_o) begin")
    push!(lines, "                inflight_q <= 1'b0;")
    push!(lines, "            end")
    push!(lines, "        end")
    push!(lines, "    end")
    push!(lines, "")

    # Start routing — only the selected datapath sees start_i
    push!(lines, "    // Start routing — one-hot to selected datapath")
    for e in entries
        push!(lines, "    assign start_$(e.funct3_id) = start_i && (funct3_i == 3'd$(e.funct3_id)) && !inflight_q;")
    end
    push!(lines, "")

    # Datapath instantiations
    push!(lines, "    // Datapath instantiations")
    for e in entries
        push!(lines, "    $(e.module_name) u_dp_$(e.funct3_id) (")
        push!(lines, "        .clk_i   (clk_i),")
        push!(lines, "        .rst_ni  (rst_ni),")
        push!(lines, "        .start_i (start_$(e.funct3_id)),")
        push!(lines, "        .rs1_i   (rs1_i),")
        push!(lines, "        .rs2_i   (rs2_i),")
        push!(lines, "        .rd_o    (rd_$(e.funct3_id)),")
        push!(lines, "        .done_o  (done_$(e.funct3_id))")
        push!(lines, "    );")
        push!(lines, "")
    end

    # Return mux — route the selected datapath's result back
    push!(lines, "    // Return mux — route selected datapath's result back")
    push!(lines, "    always_comb begin")
    push!(lines, "        rd_o   = '0;")
    push!(lines, "        done_o = 1'b0;")
    push!(lines, "        case (selected_q)")
    for e in entries
        push!(lines, "            3'd$(e.funct3_id): begin")
        push!(lines, "                rd_o   = rd_$(e.funct3_id);")
        push!(lines, "                done_o = done_$(e.funct3_id);")
        push!(lines, "            end")
    end
    push!(lines, "            default: ;")
    push!(lines, "        endcase")
    push!(lines, "    end")
    push!(lines, "")
    push!(lines, "endmodule")

    write(filepath, join(lines, "\n") * "\n")
    println("Emitted dispatcher: $filepath  ($(N) datapath(s))")
end