# VerilogEmitter.jl
# Depends on DFG_Builder types being available in the caller's scope.

export emit_verilog

# Map a DFG opcode to its SystemVerilog operator.
function op_to_sv(op::Opcode)::String
    op == OP_ADD && return "+"
    op == OP_SUB && return "-"
    op == OP_MUL && return "*"
    error("No SV operator for opcode: $op")
end

comb_wire(id::Int)        = "n$(id)_comb"
reg_wire(id::Int, c::Int) = "n$(id)_r$(c)"

# Emit a pipelined SystemVerilog module from a scheduled HWGraph.
#
# Standard Nexus datapath port list:
#   clk_i, rst_ni, start_i, rs1_i [, rs2_i ...], rd_o, done_o
#
# Precondition: schedule_asap!(graph) must be called first.
function emit_verilog(graph::HWGraph, filepath::String)
    W         = 32
    arg_ids   = graph.graph_inputs
    ret_node  = graph.nodes[graph.graph_outputs[1]]
    out_id    = ret_node.inputs[1]
    max_cycle = graph.latency

    # Group compute nodes by their scheduled cycle
    by_cycle = [Int[] for _ in 1:max_cycle]
    for (id, node) in graph.nodes
        node.op in (OP_ARG, OP_CONST, OP_RET) && continue
        push!(by_cycle[node.scheduled_cycle], id)
    end

    port_names = ["rs1_i", "rs2_i", "rs3_i", "rs4_i"]

    # Resolve a dependency node to the correct SV signal at a given cycle.
    function resolve(dep_id::Int, cyc::Int)::String
        dep = graph.nodes[dep_id]
        if dep.op == OP_ARG
            return port_names[findfirst(==(dep_id), arg_ids)]
        elseif dep.op == OP_CONST
            return "$(W)'d$(dep.const_val)"
        elseif dep.scheduled_cycle < cyc
            return reg_wire(dep_id, dep.scheduled_cycle)
        else
            return comb_wire(dep_id)
        end
    end

    lines = String[]

    push!(lines, "// Auto-generated by NexusV VerilogEmitter")
    push!(lines, "// Graph: $(graph.name)  |  Latency: $(graph.latency) cycle(s)")
    push!(lines, "")
    push!(lines, "module $(graph.name) (")
    push!(lines, "    input  logic        clk_i,")
    push!(lines, "    input  logic        rst_ni,")
    push!(lines, "    input  logic        start_i,")
    for (k, _) in enumerate(arg_ids)
        push!(lines, "    input  logic [$(W-1):0] $(port_names[k]),")
    end
    push!(lines, "    output logic [$(W-1):0] rd_o,")
    push!(lines, "    output logic        done_o")
    push!(lines, ");")
    push!(lines, "")

    # Combinational wires
    push!(lines, "    // Combinational result wires")
    for (id, node) in graph.nodes
        node.op in (OP_ARG, OP_CONST, OP_RET) && continue
        push!(lines, "    logic [$(W-1):0] $(comb_wire(id));")
    end
    push!(lines, "")

    # Pipeline register declarations
    if max_cycle > 1
        push!(lines, "    // Pipeline stage registers")
        for cyc in 1:(max_cycle-1)
            for id in by_cycle[cyc]
                push!(lines, "    logic [$(W-1):0] $(reg_wire(id, cyc));")
            end
        end
        push!(lines, "")
    end

    # done shift register / flop
    if max_cycle == 1
        push!(lines, "    logic done_r;")
    else
        push!(lines, "    logic [$(max_cycle-1):0] done_shift;")
    end
    push!(lines, "")

    # Combinational assignments
    push!(lines, "    // Combinational logic")
    for cyc in 1:max_cycle
        for id in by_cycle[cyc]
            node  = graph.nodes[id]
            sv_op = op_to_sv(node.op)
            lhs   = comb_wire(id)
            rhs_a = resolve(node.inputs[1], cyc)
            rhs_b = resolve(node.inputs[2], cyc)
            push!(lines, "    assign $lhs = $rhs_a $sv_op $rhs_b;")
        end
    end
    push!(lines, "")

    # Pipeline flip-flops
    if max_cycle > 1
        push!(lines, "    always_ff @(posedge clk_i or negedge rst_ni) begin")
        push!(lines, "        if (!rst_ni) begin")
        for cyc in 1:(max_cycle-1)
            for id in by_cycle[cyc]
                push!(lines, "            $(reg_wire(id, cyc)) <= '0;")
            end
        end
        push!(lines, "        end else begin")
        for cyc in 1:(max_cycle-1)
            for id in by_cycle[cyc]
                push!(lines, "            $(reg_wire(id, cyc)) <= $(comb_wire(id));")
            end
        end
        push!(lines, "        end")
        push!(lines, "    end")
        push!(lines, "")
    end

    # Output wire
    final_node = graph.nodes[out_id]
    final_wire = if final_node.op == OP_ARG
        port_names[findfirst(==(out_id), arg_ids)]
    elseif final_node.op == OP_CONST
        "$(W)'d$(final_node.const_val)"
    elseif max_cycle > 1 && final_node.scheduled_cycle < max_cycle
        reg_wire(out_id, final_node.scheduled_cycle)
    else
        comb_wire(out_id)
    end
    push!(lines, "    assign rd_o = $final_wire;")
    push!(lines, "")

    # done_o
    push!(lines, "    always_ff @(posedge clk_i or negedge rst_ni) begin")
    push!(lines, "        if (!rst_ni) begin")
    if max_cycle == 1
        push!(lines, "            done_r <= 1'b0;")
    else
        push!(lines, "            done_shift <= '0;")
    end
    push!(lines, "        end else begin")
    if max_cycle == 1
        push!(lines, "            done_r <= start_i;")
    else
        push!(lines, "            done_shift <= {done_shift[$(max_cycle-2):0], start_i};")
    end
    push!(lines, "        end")
    push!(lines, "    end")
    push!(lines, "")
    if max_cycle == 1
        push!(lines, "    assign done_o = done_r;")
    else
        push!(lines, "    assign done_o = done_shift[$(max_cycle-1)];")
    end
    push!(lines, "")
    push!(lines, "endmodule")

    write(filepath, join(lines, "\n") * "\n")
    println("Emitted: $filepath  (latency = $(graph.latency) cycle(s))")
end
