# DispatcherEmitter.jl
#
# Auto-generates nexus_mux.sv from a build manifest.
# Supports both stateless (one-shot compute) and stateful (command-driven)
# datapaths behind a single funct3 dispatcher.
#
# funct3 encoding:
#   0 CMD_WRITE_ADDR  latch rs1 as stateful address
#   1 CMD_WRITE_DATA  latch rs1 as stateful write data, pulse we
#   2 CMD_START       assert start_i on stateful datapath
#   3–7 stateless datapath select (#3 = mac_plus_5, #4 = crc_step, ...)

export DatapathEntry, StatefulEntry, emit_dispatcher

# Metadata for one stateless datapath (one-shot compute).
struct DatapathEntry
    module_name::String      # "mac_plus_5"
    funct3_id::Int           # 3–7, dispatch key from CV-X-IF instruction
    latency::Int             # pipeline depth in cycles
    is_stateful::Bool        # always false for this type
    file_path::String        # relative to hw/rtl/, e.g. "mac_plus_5.sv"
end

# Metadata for the ONE stateful datapath behind the mux.
# funct3 0-2 are reserved for stateful commands.
struct StatefulEntry
    module_name::String      # e.g. "nexus_mont_adapter"
    latency::Int             # nominal pipeline depth
    file_path::String        # relative to hw/rtl/
end

# Generate nexus_mux.sv from a stateful entry + list of stateless entries.
#
# Stateful interface (if present):
#   addr_i, wdata_i, we_i — driven by CMD_WRITE_ADDR / CMD_WRITE_DATA
#   start_i, done_o, rd_o  — driven by CMD_START
#
# Stateless interfaces:
#   start_i, rs1_i, rs2_i, rd_o, done_o
function emit_dispatcher(stateful::Union{StatefulEntry,Nothing},
    stateless::Vector{DatapathEntry},
    filepath::String)
    W = 32
    N = length(stateless)
    has_stateful = stateful !== nothing

    # Validate stateless funct3 IDs (3–7)
    for e in stateless
        @assert 3 <= e.funct3_id <= 7 "Stateless funct3_id must be in 3..7, got $(e.funct3_id)"
    end
    ids = [e.funct3_id for e in stateless]
    length(ids) == length(unique(ids)) || error("Duplicate stateless funct3_id")
    N > 0 || has_stateful || error("Must have at least one entry")

    lines = String[]

    push!(lines, "// Auto-generated by NexusV DispatcherEmitter")
    if has_stateful
        push!(lines, "// 1 stateful + $(N) stateless datapath(s) behind mux")
    else
        push!(lines, "// $(N) stateless datapath(s) behind mux")
    end
    push!(lines, "")

    # Command encoding
    if has_stateful
        push!(lines, "    // Stateful command encoding (funct3 0–2)")
        push!(lines, "    localparam logic [2:0] CMD_WRITE_ADDR = 3'd0;")
        push!(lines, "    localparam logic [2:0] CMD_WRITE_DATA = 3'd1;")
        push!(lines, "    localparam logic [2:0] CMD_START      = 3'd2;")
        push!(lines, "")
    end

    push!(lines, "module nexus_mux (")
    push!(lines, "    input  logic        clk_i,")
    push!(lines, "    input  logic        rst_ni,")
    push!(lines, "    input  logic        start_i,")
    push!(lines, "    input  logic        stall_i,")
    push!(lines, "    input  logic [2:0]  funct3_i,")
    push!(lines, "    input  logic [$(W-1):0] rs1_i,")
    push!(lines, "    input  logic [$(W-1):0] rs2_i,")
    push!(lines, "    output logic [$(W-1):0] rd_o,")
    push!(lines, "    output logic        done_o")
    if has_stateful
        push!(lines, ",")
        push!(lines, "    // Scratchpad Port B passthrough")
        push!(lines, "    output logic [15:0] sp_addr_o,")
        push!(lines, "    output logic [$(W-1):0] sp_wdata_o,")
        push!(lines, "    output logic        sp_we_o,")
        push!(lines, "    input  logic [$(W-1):0] sp_rdata_i")
    end
    push!(lines, ");")
    push!(lines, "")

    # Stateful registers
    if has_stateful
        push!(lines, "    // Stateful configuration registers (latched via commands)")
        push!(lines, "    logic [$(W-1):0] stateful_addr_q;")
        push!(lines, "    logic [$(W-1):0] stateful_wdata_q;")
        push!(lines, "    logic           stateful_we;       // pulsed on CMD_WRITE_DATA")
        push!(lines, "    logic           stateful_start;    // pulsed on CMD_START")
        push!(lines, "    logic           stateful_done;")
        push!(lines, "    logic [$(W-1):0] stateful_rd;")
        push!(lines, "")
        push!(lines, "    always_ff @(posedge clk_i or negedge rst_ni) begin")
        push!(lines, "        if (!rst_ni) begin")
        push!(lines, "            stateful_addr_q  <= '0;")
        push!(lines, "            stateful_wdata_q <= '0;")
        push!(lines, "        end else if (start_i && !done_o) begin")
        push!(lines, "            unique case (funct3_i)")
        push!(lines, "                CMD_WRITE_ADDR: stateful_addr_q  <= rs1_i;")
        push!(lines, "                CMD_WRITE_DATA: stateful_wdata_q <= rs1_i;")
        push!(lines, "                default: ;")
        push!(lines, "            endcase")
        push!(lines, "        end")
        push!(lines, "    end")
        push!(lines, "")
        push!(lines, "    // Command pulse generators (1 cycle, qualified by start_i)")
        push!(lines, "    assign stateful_we    = start_i && !done_o && (funct3_i == CMD_WRITE_DATA);")
        push!(lines, "    assign stateful_start = start_i && !done_o && (funct3_i == CMD_START);")
        push!(lines, "")
    end

    # ── Stateless per-datapath signals ────────────────────────────────────
    push!(lines, "    // Per-datapath handshake signals")
    for e in stateless
        push!(lines, "    logic        start_$(e.funct3_id);")
        push!(lines, "    logic        done_$(e.funct3_id);")
        push!(lines, "    logic [$(W-1):0] rd_$(e.funct3_id);")
    end
    push!(lines, "")

    # Selection latch
    push!(lines, "    // Dispatch selection latch remembers which path is busy")
    push!(lines, "    logic [2:0] selected_q;")
    push!(lines, "    logic       inflight_q;")
    push!(lines, "")
    push!(lines, "    always_ff @(posedge clk_i or negedge rst_ni) begin")
    push!(lines, "        if (!rst_ni) begin")
    push!(lines, "            selected_q <= '0;")
    push!(lines, "            inflight_q <= 1'b0;")
    push!(lines, "        end else begin")
    push!(lines, "            if (start_i && !inflight_q) begin")
    push!(lines, "                selected_q <= funct3_i;")
    push!(lines, "                inflight_q <= 1'b1;")
    push!(lines, "            end else if (done_o) begin")
    push!(lines, "                inflight_q <= 1'b0;")
    push!(lines, "            end")
    push!(lines, "        end")
    push!(lines, "    end")
    push!(lines, "")

    # Stateless start routing
    push!(lines, "    // Stateless start routing — one-hot based on funct3 >= 3")
    for e in stateless
        push!(lines, "    assign start_$(e.funct3_id) = start_i && (funct3_i == 3'd$(e.funct3_id)) && !inflight_q;")
    end
    push!(lines, "")

    # Stateful datapath instantiation
    if has_stateful
        push!(lines, "    // Stateful datapath — commands routed via funct3 0-2")
        push!(lines, "    $(stateful.module_name) u_stateful (")
        push!(lines, "        .clk_i   (clk_i),")
        push!(lines, "        .rst_ni  (rst_ni),")
        push!(lines, "        .stall_i (stall_i),")
        push!(lines, "        .start_i (stateful_start),")
        push!(lines, "        .rs1_i   (rs1_i),")
        push!(lines, "        .rs2_i   (rs2_i),")
        push!(lines, "        .addr_i  (stateful_addr_q),")
        push!(lines, "        .wdata_i (stateful_wdata_q),")
        push!(lines, "        .we_i    (stateful_we),")
        push!(lines, "        .rd_o    (stateful_rd),")
        push!(lines, "        .done_o  (stateful_done),")
        push!(lines, "        .sp_addr_o (sp_addr_o),")
        push!(lines, "        .sp_we_o   (sp_we_o),")
        push!(lines, "        .sp_wdata_o(sp_wdata_o),")
        push!(lines, "        .sp_rdata_i(sp_rdata_i)")
        push!(lines, "    );")
        push!(lines, "")
    end

    # Stateless datapath instantiations
    push!(lines, "    // Stateless datapath instantiations")
    for e in stateless
        push!(lines, "    $(e.module_name) u_dp_$(e.funct3_id) (")
        push!(lines, "        .clk_i   (clk_i),")
        push!(lines, "        .rst_ni  (rst_ni),")
        push!(lines, "        .start_i (start_$(e.funct3_id)),")
        push!(lines, "        .stall_i (stall_i),")
        push!(lines, "        .rs1_i   (rs1_i),")
        push!(lines, "        .rs2_i   (rs2_i),")
        push!(lines, "        .rd_o    (rd_$(e.funct3_id)),")
        push!(lines, "        .done_o  (done_$(e.funct3_id))")
        push!(lines, "    );")
        push!(lines, "")
    end

    # Return mux
    push!(lines, "    // Return mux — route back from the selected path")
    push!(lines, "    always_comb begin")
    push!(lines, "        rd_o   = '0;")
    push!(lines, "        done_o = 1'b0;")
    if has_stateful
        push!(lines, "        case (selected_q)")
        push!(lines, "            CMD_WRITE_ADDR,")
        push!(lines, "            CMD_WRITE_DATA,")
        push!(lines, "            CMD_START: begin")
        push!(lines, "                rd_o   = stateful_rd;")
        push!(lines, "                done_o = stateful_done;")
        push!(lines, "            end")
    else
        push!(lines, "        case (selected_q)")
    end
    for e in stateless
        push!(lines, "            3'd$(e.funct3_id): begin")
        push!(lines, "                rd_o   = rd_$(e.funct3_id);")
        push!(lines, "                done_o = done_$(e.funct3_id);")
        push!(lines, "            end")
    end
    push!(lines, "            default: ;")
    push!(lines, "        endcase")
    push!(lines, "    end")
    push!(lines, "")
    push!(lines, "endmodule")

    write(filepath, join(lines, "\n") * "\n")
    summary = has_stateful ? "1 stateful + $(N) stateless" : "$(N) stateless"
    println("Emitted dispatcher: $filepath  ($(summary) datapath(s))")
end